[platformio]
; Hiermit sagen wir PlatformIO, dass der Quellcode im aktuellen Ordner (Root) liegt,
; sodass die .ino-Datei nicht in einen unterordneten "src" Ordner verschoben werden muss.

[env:esp32-audio-kit]
platform = espressif32
board = esp32dev
board_build.partitions = min_spiffs.csv
framework = arduino
monitor_speed = 115200

# Konfiguration und Speicher-Einstellungen für das Audio Kit (ESP32-A1S Modul)
board_build.mcu = esp32
board_build.f_cpu = 240000000L

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D AI_THINKER_ES8388_VOLUME_HACK=1
    # Verhindert, dass PIO andere unnötige Libs autoamtisch einbindet und fehlschlägt
    -D AUDIOKIT_BOARD=5

lib_deps =
    # MQTT
    knolleary/PubSubClient@^2.8
    # Phil Schatzmann's Audio Libs
    bblanchon/ArduinoJson @ ^7.0.4
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-audio-driver.git
    https://github.com/pschatzmann/arduino-libhelix.git
    adafruit/Adafruit NeoPixel
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
